name: CI Build ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ubuntu ${{ matrix.compiler }} ${{ matrix.sanitizer }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [clang, gcc]
        sanitizer: [none, asan, valgrind]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Valgrind (if needed)
        if: matrix.sanitizer == 'valgrind'
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Build and run tests (Debug + Release)
        run: |
          # Set sanitizer flags
          if [ "${{ matrix.sanitizer }}" == "asan" ]; then
            export ASAN=1
          fi
          if [ "${{ matrix.sanitizer }}" == "valgrind" ]; then
            export VALGRIND=1
          fi

          for BUILD_TYPE in Debug Release; do
            echo "=== Building $BUILD_TYPE ==="

            # The ,, lowercases it to build-debug and build-release
            export BUILD_DIR=build-${BUILD_TYPE,,} 
            
            CMAKE_FLAGS=("-G" "Ninja" "-DCMAKE_BUILD_TYPE=$BUILD_TYPE" "-DCMAKE_C_COMPILER=${{ matrix.compiler }}")

            cmake -S . -B $BUILD_DIR "${CMAKE_FLAGS[@]}"
            cmake --build $BUILD_DIR --config=$BUILD_TYPE

            echo "=== Running tests ($BUILD_TYPE) ==="
            TEST_EXE=$(find $BUILD_DIR -type f \( -name "smoketest" -o -name "smoketest.exe" \) | head -n 1)

            if [ ! -z "$VALGRIND" ]; then
              valgrind "$TEST_EXE"
            else
              "$TEST_EXE"
            fi
          done

        env:
          SHUFFLES: 10
